#All constants were extracted from the dataset
CAR_MAKES = [
    "Acura",
    "AstonMartin",
    "Audi",
    "BMW",
    "Bentley",
    "Buick",
    "Cadillac",
    "Chevrolet",
    "Chrysler",
    "Daewoo",
    "Dodge",
    "FIAT",
    "Ferrari",
    "Fisker",
    "Ford",
    "GMC",
    "Geo",
    "HUMMER",
    "Honda",
    "Hyundai",
    "Infiniti",
    "Isuzu",
    "Jaguar",
    "Jeep",
    "Kia",
    "Lamborghini",
    "LandRover",
    "Lexus",
    "Lincoln",
    "Lotus",
    "MINI",
    "Maserati",
    "Mazda",
    "Mercedes-Benz",
    "Mercury",
    "Mitsubishi",
    "Nissan",
    "Oldsmobile",
    "Plymouth",
    "Pontiac",
    "Porsche",
    "Ram",
    "Rolls-Royce",
    "Saab",
    "Saturn",
    "Scion",
    "Subaru",
    "Suzuki",
    "Tesla",
    "Toyota",
    "Volkswagen",
    "Volvo",
    "smart",
]


CAR_MODELS = [
    "1 Series",
    "1500",
    "190-Class",
    "2 Series",
    "200",
    "200SX",
    "2500",
    "3",
    "3 Series",
    "3 Series Gran Turismo",
    "300",
    "300-Class",
    "3000GT",
    "300M",
    "300ZX",
    "3500",
    "350Z",
    "360",
    "370Z",
    "4 Series",
    "4 Series Gran Coupe",
    "400-Class",
    "420-Class",
    "458 Italia",
    "4Runner",
    "5 Series",
    "5 Series Gran Turismo",
    "500",
    "500-Class",
    "500L",
    "500e",
    "6",
    "6 Series",
    "6 Series Gran Coupe",
    "626",
    "7 Series",
    "8 Series",
    "850",
    "9-2X",
    "9-3",
    "9-5",
    "9-7X",
    "911",
    "940",
    "960",
    "A3",
    "A4",
    "A5",
    "A6",
    "A7",
    "A8",
    "ATS",
    "Acadia",
    "Accent",
    "Accord",
    "Accord Crosstour",
    "Accord Hybrid",
    "Achieva",
    "ActiveHybrid 5",
    "ActiveHybrid 7",
    "ActiveHybrid X6",
    "Aerio",
    "Alero",
    "Altima",
    "Altima Hybrid",
    "Amanti",
    "Amigo",
    "Armada",
    "Ascender",
    "Aspen",
    "Aspire",
    "Astra",
    "Astro",
    "Astro Cargo",
    "Aura",
    "Aura Hybrid",
    "Aurora",
    "Avalanche",
    "Avalon",
    "Avalon Hybrid",
    "Avenger",
    "Aveo",
    "Aviator",
    "Axiom",
    "Azera",
    "Aztek",
    "B-Class Electric Drive",
    "B-Series",
    "B-Series Pickup",
    "B-Series Truck",
    "B9 Tribeca",
    "BRZ",
    "Baja",
    "Beetle",
    "Beetle Convertible",
    "Black Diamond Avalanche",
    "Blackwood",
    "Blazer",
    "Bonneville",
    "Borrego",
    "Boxster",
    "Bravada",
    "Breeze",
    "C-Class",
    "C-Max Energi",
    "C-Max Hybrid",
    "C/K 1500 Series",
    "C/K 2500 Series",
    "C/K 3500 Series",
    "C/V Cargo Van",
    "C/V Tradesman",
    "C30",
    "C70",
    "CC",
    "CL",
    "CL-Class",
    "CLA-Class",
    "CLK-Class",
    "CLS-Class",
    "CR-V",
    "CR-Z",
    "CT 200h",
    "CTS",
    "CTS Coupe",
    "CTS Wagon",
    "CTS-V",
    "CTS-V Coupe",
    "CTS-V Wagon",
    "CV Tradesman",
    "CX-5",
    "CX-7",
    "CX-9",
    "Cabrio",
    "Cabriolet",
    "Cadenza",
    "Caliber",
    "California",
    "Camaro",
    "Camry",
    "Camry Hybrid",
    "Camry Solara",
    "Canyon",
    "Caprice",
    "Captiva Sport",
    "Caravan",
    "Catera",
    "Cavalier",
    "Cayenne",
    "Cayman",
    "Cayman S",
    "Celica",
    "Century",
    "Challenger",
    "Charger",
    "Cherokee",
    "Cirrus",
    "Civic",
    "Civic del Sol",
    "Classic",
    "Cobalt",
    "Colorado",
    "Commander",
    "Compass",
    "Concorde",
    "Continental",
    "Continental Flying Spur",
    "Continental Flying Spur Speed",
    "Continental GT",
    "Continental GT Speed",
    "Continental GTC",
    "Continental GTC Speed",
    "Continental Supersports",
    "Contour",
    "Cooper",
    "Cooper Clubman",
    "Cooper Countryman",
    "Cooper Coupe",
    "Cooper Paceman",
    "Cooper Roadster",
    "Corolla",
    "Corsica",
    "Corvette",
    "Corvette Stingray",
    "Cougar",
    "Coupe",
    "Crossfire",
    "Crosstour",
    "Crown Victoria",
    "Cruze",
    "Cube",
    "Cutlass",
    "Cutlass Ciera",
    "Cutlass Supreme",
    "DB9",
    "DTS",
    "Dakota",
    "Dart",
    "DeVille",
    "Diamante",
    "Discovery",
    "Discovery Series II",
    "Durango",
    "E-150",
    "E-250",
    "E-350",
    "E-Class",
    "E-Series Van",
    "E-Series Wagon",
    "ECHO",
    "ELR",
    "ES 300",
    "ES 300h",
    "ES 330",
    "ES 350",
    "EX",
    "EX35",
    "Eclipse",
    "Eclipse Spyder",
    "Econoline Cargo",
    "Econoline Wagon",
    "Edge",
    "Eighty-Eight",
    "Eighty-Eight Royale",
    "Elantra",
    "Elantra Coupe",
    "Elantra GT",
    "Elantra Touring",
    "Eldorado",
    "Element",
    "Enclave",
    "Encore",
    "Endeavor",
    "Entourage",
    "Envoy",
    "Envoy XL",
    "Envoy XUV",
    "Eos",
    "Equator",
    "Equinox",
    "Equus",
    "Escalade",
    "Escalade ESV",
    "Escalade EXT",
    "Escalade Hybrid",
    "Escape",
    "Escape Hybrid",
    "Escort",
    "Esteem",
    "EuroVan",
    "Excursion",
    "Exige",
    "Expedition",
    "Expedition EL",
    "Explorer",
    "Explorer Sport",
    "Explorer Sport Trac",
    "Express",
    "Express Cargo",
    "F-150",
    "F-150 Heritage",
    "F-150 SVT Lightning",
    "F-250",
    "F-250 Super Duty",
    "F-350 Super Duty",
    "F-450 Super Duty",
    "F-TYPE",
    "F430",
    "FJ Cruiser",
    "FR-S",
    "FX",
    "FX35",
    "FX45",
    "FX50",
    "Fiesta",
    "Firebird",
    "Fit",
    "Five Hundred",
    "Fleetwood",
    "Flex",
    "Flying Spur",
    "Focus",
    "Focus ST",
    "Forenza",
    "Forester",
    "Forte",
    "Freelander",
    "Freestar",
    "Freestyle",
    "Frontier",
    "Fusion",
    "Fusion Energi",
    "Fusion Hybrid",
    "G Convertible",
    "G Coupe",
    "G Sedan",
    "G-Class",
    "G20",
    "G3",
    "G35",
    "G37",
    "G37 Convertible",
    "G37 Coupe",
    "G5",
    "G6",
    "G8",
    "GL-Class",
    "GLA-Class",
    "GLI",
    "GLK-Class",
    "GS 300",
    "GS 350",
    "GS 400",
    "GS 430",
    "GS 450h",
    "GS 460",
    "GT-R",
    "GTI",
    "GTO",
    "GX 460",
    "GX 470",
    "Galant",
    "Gallardo",
    "Genesis",
    "Genesis Coupe",
    "Ghibli",
    "Ghost",
    "Golf",
    "Golf GTI",
    "Golf R",
    "GranSport",
    "GranTurismo",
    "GranTurismo Convertible",
    "Grand Am",
    "Grand Caravan",
    "Grand Cherokee",
    "Grand Cherokee SRT",
    "Grand Marquis",
    "Grand Prix",
    "Grand Vitara",
    "H1",
    "H2",
    "H2 SUT",
    "H3",
    "H3T",
    "HHR",
    "HS 250h",
    "Highlander",
    "Highlander Hybrid",
    "I30",
    "I35",
    "ILX",
    "ION",
    "IS 250",
    "IS 250 C",
    "IS 300",
    "IS 350",
    "IS 350 C",
    "IS F",
    "Impala",
    "Impala Limited",
    "Impreza",
    "Impreza WRX",
    "Insight",
    "Integra",
    "Intrepid",
    "Intrigue",
    "J30",
    "JX",
    "Jetta",
    "Jetta GLI",
    "Jetta Hybrid",
    "Jetta SportWagen",
    "Jimmy",
    "Journey",
    "Juke",
    "K900",
    "Karma",
    "Kizashi",
    "L-Series",
    "L300",
    "LHS",
    "LR2",
    "LR3",
    "LR4",
    "LS",
    "LS 400",
    "LS 430",
    "LS 460",
    "LS 600h L",
    "LX 450",
    "LX 470",
    "LX 570",
    "LaCrosse",
    "Lancer",
    "Lancer Evolution",
    "Lancer Sportback",
    "Land Cruiser",
    "Le Baron",
    "LeSabre",
    "Leaf",
    "Legacy",
    "Leganza",
    "Legend",
    "Liberty",
    "Lucerne",
    "Lumina",
    "M",
    "M-Class",
    "M3",
    "M35",
    "M37",
    "M4",
    "M45",
    "M5",
    "M56",
    "M6",
    "M6 Gran Coupe",
    "MDX",
    "MKC",
    "MKS",
    "MKT",
    "MKX",
    "MKZ",
    "MKZ Hybrid",
    "ML55 AMG",
    "MPV",
    "MR2 Spyder",
    "MX-5 Miata",
    "Macan",
    "Magnum",
    "Malibu",
    "Malibu Classic",
    "Malibu Hybrid",
    "Malibu Maxx",
    "Marauder",
    "Mariner",
    "Mariner Hybrid",
    "Mark LT",
    "Mark VIII",
    "Matrix",
    "Maxima",
    "Mazda2",
    "Mazda3",
    "Mazda5",
    "Mazda6",
    "Mazdaspeed 3",
    "Mazdaspeed MX-5 Miata",
    "Mazdaspeed Mazda3",
    "Mazdaspeed Mazda6",
    "Mazdaspeed Protege",
    "Mazdaspeed3",
    "Metro",
    "Milan",
    "Milan Hybrid",
    "Millenia",
    "Mirage",
    "Model S",
    "Montana",
    "Montana SV6",
    "Monte Carlo",
    "Montego",
    "Monterey",
    "Montero",
    "Montero Sport",
    "Mountaineer",
    "Murano",
    "Murano CrossCabriolet",
    "Mustang",
    "Mustang SVT Cobra",
    "Mystique",
    "NV",
    "NV Cargo",
    "NV Passenger",
    "NV200",
    "Navigator",
    "Navigator L",
    "Neon",
    "New Beetle",
    "Nitro",
    "Nubira",
    "Odyssey",
    "Optima",
    "Outback",
    "Outlander",
    "Outlander Sport",
    "Outlook",
    "PT Cruiser",
    "Pacifica",
    "Panamera",
    "Park Avenue",
    "Paseo",
    "Passat",
    "Passport",
    "Pathfinder",
    "Patriot",
    "Phaeton",
    "Pickup",
    "Pilot",
    "Prelude",
    "Prius",
    "Prius Plug-in",
    "Prius c",
    "Prius v",
    "Prizm",
    "Promaster Cargo Van",
    "Protege",
    "Protege5",
    "Prowler",
    "Q3",
    "Q45",
    "Q5",
    "Q50",
    "Q60 Convertible",
    "Q60 Coupe",
    "Q7",
    "Q70",
    "QX",
    "QX4",
    "QX50",
    "QX56",
    "QX60",
    "QX70",
    "QX80",
    "Quattroporte",
    "Quest",
    "R-Class",
    "R32",
    "R8",
    "RAV4",
    "RC 350",
    "RC F",
    "RDX",
    "RL",
    "RLX",
    "RS 4",
    "RS 5",
    "RS 6",
    "RS 7",
    "RSX",
    "RX 300",
    "RX 330",
    "RX 350",
    "RX 400h",
    "RX 450h",
    "RX-8",
    "Rabbit",
    "Raider",
    "Rainier",
    "Ram Cargo",
    "Ram Pickup 1500",
    "Ram Pickup 2500",
    "Ram Pickup 3500",
    "Ram Van",
    "Range Rover",
    "Range Rover Evoque",
    "Range Rover Sport",
    "Ranger",
    "Rapide",
    "Regal",
    "Regency",
    "Relay",
    "Rendezvous",
    "Reno",
    "Ridgeline",
    "Rio",
    "Riviera",
    "Roadmaster",
    "Rodeo",
    "Rodeo Sport",
    "Rogue",
    "Rogue Select",
    "Rondo",
    "Routan",
    "S-10",
    "S-10 Blazer",
    "S-Class",
    "S-Series",
    "S-Type",
    "S2000",
    "S4",
    "S40",
    "S5",
    "S6",
    "S60",
    "S7",
    "S70",
    "S8",
    "S80",
    "S90",
    "SC 300",
    "SC 400",
    "SC 430",
    "SL-Class",
    "SLK-Class",
    "SLS AMG",
    "SLS AMG GT",
    "SQ5",
    "SRX",
    "SS",
    "SSR",
    "STS",
    "STS-V",
    "SX4",
    "Sable",
    "Safari",
    "Safari Cargo",
    "Santa Fe",
    "Santa Fe Sport",
    "Savana",
    "Savana Cargo",
    "Sebring",
    "Sedona",
    "Sentra",
    "Sephia",
    "Sequoia",
    "Seville",
    "Shelby GT500",
    "Sidekick",
    "Sienna",
    "Sierra 1500",
    "Sierra 1500 Classic",
    "Sierra 1500 Hybrid",
    "Sierra 1500HD",
    "Sierra 2500",
    "Sierra 2500HD",
    "Sierra 2500HD Classic",
    "Sierra 3500",
    "Sierra 3500HD",
    "Silhouette",
    "Silverado 1500",
    "Silverado 1500 Classic",
    "Silverado 1500 Hybrid",
    "Silverado 1500HD",
    "Silverado 2500",
    "Silverado 2500HD",
    "Silverado 2500HD Classic",
    "Silverado 3500",
    "Silverado 3500 Classic",
    "Silverado 3500HD",
    "Sky",
    "Solstice",
    "Sonata",
    "Sonata Hybrid",
    "Sonic",
    "Sonoma",
    "Sorento",
    "Soul",
    "Spark",
    "Spark EV",
    "Spectra",
    "Spirit",
    "Sportage",
    "Sprinter",
    "Sprinter Cargo",
    "Spyder",
    "Stratus",
    "Suburban",
    "Sunfire",
    "T100",
    "TL",
    "TLX",
    "TSX",
    "TSX Sport Wagon",
    "TT",
    "TT RS",
    "TTS",
    "Tacoma",
    "Tahoe",
    "Tahoe Hybrid",
    "Tahoe Limited/Z71",
    "Taurus",
    "Taurus X",
    "Tempo",
    "Tercel",
    "Terrain",
    "Terraza",
    "Thunderbird",
    "Tiburon",
    "Tiguan",
    "Titan",
    "Torrent",
    "Touareg",
    "Touareg 2",
    "Town Car",
    "Town and Country",
    "Tracer",
    "Tracker",
    "TrailBlazer",
    "TrailBlazer EXT",
    "Transit Connect",
    "Transit Van",
    "Transit Wagon",
    "Traverse",
    "Tribeca",
    "Tribute",
    "Tribute Hybrid",
    "Trooper",
    "Truck",
    "Tucson",
    "Tundra",
    "Uplander",
    "V40",
    "V50",
    "V60",
    "V70",
    "V8 Vantage",
    "VUE",
    "VUE Hybrid",
    "Veloster",
    "Venture",
    "Venza",
    "Veracruz",
    "Verano",
    "Verona",
    "Versa",
    "Versa Note",
    "Vibe",
    "Villager",
    "Viper",
    "Vitara",
    "Volt",
    "Voyager",
    "WRX",
    "Windstar",
    "Windstar Cargo",
    "Wrangler",
    "X-Type",
    "X1",
    "X3",
    "X4",
    "X5",
    "X5 M",
    "X6",
    "X6 M",
    "XC",
    "XC60",
    "XC70",
    "XC90",
    "XF",
    "XG300",
    "XG350",
    "XJ",
    "XJ-Series",
    "XK",
    "XK-Series",
    "XL-7",
    "XL7",
    "XLR",
    "XTS",
    "XV Crosstrek",
    "Xterra",
    "Yaris",
    "Yukon",
    "Yukon Denali",
    "Yukon Hybrid",
    "Yukon XL",
    "Z3",
    "Z4",
    "Z4 M",
    "ZDX",
    "Zephyr",
    "accord",
    "allroad",
    "allroad quattro",
    "envoy",
    "fortwo",
    "i-MiEV",
    "i-Series",
    "i8",
    "iQ",
    "malibu",
    "mdx",
    "tC",
    "xA",
    "xB",
    "xD",
]


CAR_TRIMS = [
    "!",
    "(1999.5) XE",
    "+",
    "1",
    "1.6",
    "1.6 Base",
    "1.6 S",
    "1.6 S Plus",
    "1.6 SL",
    "1.6 SV",
    "1.8",
    "1.8 Base",
    "1.8 Krom",
    "1.8 S",
    "1.8 S Krom Edition",
    "1.8 SL",
    "1.8 TFSI Premium",
    "1.8 TFSI Premium Plus",
    "1.8T",
    "1.8T Avant quattro",
    "1.8T Classic",
    "1.8T quattro",
    "1.9",
    "10th Anniversary",
    "128i",
    "128i SULEV",
    "135i",
    "135is",
    "150 Low Roof",
    "1500",
    "1500 High Roof",
    "1500 LS",
    "1500 LT",
    "1500 LT1",
    "1500 LTZ",
    "1500 Low Roof",
    "1500 Maxi",
    "1500 S",
    "1500 SLE",
    "1500 SLT",
    "1500 SV",
    "1794",
    "1794 FFV",
    "180hp",
    "180hp quattro",
    "190E 2.3",
    "1LS Fleet",
    "1LT",
    "1LT Fleet",
    "1SS",
    "2",
    "2+2",
    "2.0 S",
    "2.0 SL",
    "2.0 SR",
    "2.0 TDI Premium",
    "2.0 TDI Premium Plus",
    "2.0 TFSI Premium Plus quattro",
    "2.0 TFSI Prestige quattro",
    "2.0L TDI",
    "2.0T",
    "2.0T Avant Premium quattro",
    "2.0T Avant quattro",
    "2.0T PZEV",
    "2.0T PZEV Premium",
    "2.0T Premium",
    "2.0T Premium Avant quattro",
    "2.0T Premium Plus",
    "2.0T Premium Plus quattro",
    "2.0T Premium quattro",
    "2.0T Prestige",
    "2.0T Prestige quattro",
    "2.0T R-Spec",
    "2.0T SportCombi",
    "2.0T Turbo",
    "2.0T Turbo PZEV",
    "2.0T White Turbo Launch Edition",
    "2.0T White Turbo Launch Edition PZEV",
    "2.0T quattro",
    "2.0XT Premium",
    "2.0XT Touring",
    "2.0i",
    "2.0i Limited PZEV",
    "2.0i PZEV",
    "2.0i Premium PZEV",
    "2.0i Sport Limited PZEV",
    "2.0i Sport Premium PZEV",
    "2.2",
    "2.2 Premium",
    "2.3",
    "2.3 Premium",
    "2.3t",
    "2.4",
    "2.4M",
    "2.4T",
    "2.4i",
    "2.5",
    "2.5 GT",
    "2.5 GT Limited",
    "2.5 I",
    "2.5 I Limited",
    "2.5 PZEV",
    "2.5 Premium",
    "2.5 RS",
    "2.5 S",
    "2.5 SL",
    "2.5 SV",
    "2.5 TS",
    "2.5 X",
    "2.5 X L.L.Bean Edition",
    "2.5 X Premium Package",
    "2.5 XT",
    "2.5 XT Limited",
    "2.5 i",
    "2.5GT Limited",
    "2.5I",
    "2.5I Limited",
    "2.5L",
    "2.5L Blush Edition",
    "2.5L Blush Edition PZEV",
    "2.5L Final Edition",
    "2.5L Final Edition PZEV",
    "2.5L PZEV",
    "2.5L Red Rock Edition",
    "2.5L Red Rock Edition PZEV",
    "2.5T",
    "2.5T SE",
    "2.5X",
    "2.5X Limited",
    "2.5X Limited PZEV",
    "2.5X PZEV",
    "2.5X Premium",
    "2.5X Premium PZEV",
    "2.5X Touring",
    "2.5X Touring PZEV",
    "2.5XT",
    "2.5XT Limited",
    "2.5XT Premium",
    "2.5XT Touring",
    "2.5i",
    "2.5i Limited",
    "2.5i Limited PZEV",
    "2.5i PZEV",
    "2.5i Premium",
    "2.5i Premium PZEV",
    "2.5i Special Edition",
    "2.5i Sport",
    "2.5i Sport PZEV",
    "2.5i Touring PZEV",
    "2.7T S-Line quattro",
    "2.7T quattro",
    "2.8",
    "2.8 Avant quattro",
    "2.8 quattro",
    "2.9",
    "20th Anniversary Edition",
    "225hp quattro",
    "228i",
    "250 High Roof",
    "250 Low Roof",
    "250 Medium Roof",
    "2500",
    "2500 118 WB",
    "2500 140 WB",
    "2500 144 WB",
    "2500 144 WB Cargo",
    "2500 144 WB Crew",
    "2500 144 WB Passenger",
    "2500 170 WB",
    "2500 170 WB Cargo",
    "2500 170 WB Passenger",
    "2500 High Ceiling 118 WB",
    "2500 High Roof",
    "2500 High Roof 140 WB",
    "2500 High Roof 158 WB",
    "2500 LS",
    "2500 LT",
    "2500 S",
    "2500 SH Ceiling 140 WB",
    "2500 SLE",
    "2500 SV",
    "250hp quattro",
    "25th Anniversary",
    "2LS Fleet",
    "2LT",
    "2SS",
    "3",
    "3.0 Avant quattro",
    "3.0 Premium",
    "3.0 R",
    "3.0 R L.L.Bean Edition",
    "3.0 R Limited",
    "3.0 R VDC Limited",
    "3.0 quattro",
    "3.0L",
    "3.0L Sportwagon",
    "3.0R Limited",
    "3.0T Premium Plus quattro",
    "3.0T Premium quattro",
    "3.0T Prestige quattro",
    "3.0T S line Prestige quattro",
    "3.0T quattro",
    "3.0i",
    "3.0si",
    "3.2",
    "3.2 Avant quattro",
    "3.2 Premier Plus",
    "3.2 Premium",
    "3.2 Premium Plus quattro",
    "3.2 Premium quattro",
    "3.2 R-Design",
    "3.2 Special Edition",
    "3.2 Type-S",
    "3.2 quattro",
    "3.2L",
    "3.5",
    "3.5 Premium",
    "3.5 S",
    "3.5 SE",
    "3.5 SE-R",
    "3.5 SL",
    "3.5 SR",
    "3.5 SV",
    "3.5 Special Edition",
    "3.5L",
    "3.5XS",
    "3.6",
    "3.6 4Motion",
    "3.6 Premium quattro",
    "3.6 quattro",
    "3.6R Limited",
    "3.6R Premium",
    "3.6R Touring",
    "3.8",
    "3.8 Grand Touring",
    "3.8 R-Spec",
    "3.8 Track",
    "3.8 Ultimate",
    "300E",
    "300E 2.8",
    "300SE",
    "300SL",
    "318i",
    "318ti",
    "320i",
    "320i xDrive",
    "323Ci",
    "323i",
    "323iT",
    "323is",
    "325Ci",
    "325i",
    "325is",
    "325xi",
    "328Ci",
    "328d",
    "328d xDrive",
    "328i",
    "328i SULEV",
    "328i xDrive",
    "328i xDrive SULEV",
    "328is",
    "328xi",
    "330Ci",
    "330i",
    "330xi",
    "335d",
    "335i",
    "335i xDrive",
    "335is",
    "335xi",
    "350 XL High Roof",
    "350 XL Low Roof",
    "350 XL Medium Roof",
    "3500",
    "3500 170 WB",
    "3500 170 WB Cargo",
    "3500 High Roof 140 WB",
    "3500 High Roof 158 WB",
    "3500 S",
    "3500 SH Ceiling 158 WB",
    "3500 SV",
    "4",
    "4.0 S",
    "4.0 SE",
    "4.0T quattro",
    "4.2",
    "4.2 Premium quattro",
    "4.2 Prestige quattro",
    "4.2 quattro",
    "4.2 quattro Spyder",
    "4.2i",
    "4.4i",
    "4.6",
    "4.6 HSE",
    "4.6 SE",
    "4.6 Vitesse",
    "4.6is",
    "4.8i",
    "4.8is",
    "400SEL",
    "420SEL",
    "427",
    "428i",
    "428i SULEV",
    "428i xDrive",
    "428i xDrive SULEV",
    "435i",
    "435i xDrive",
    "454SS",
    "4S",
    "5",
    "5-Passenger",
    "5.0 R-Spec",
    "5.2 quattro",
    "5.2 quattro Spyder",
    "5.3i",
    "500SL",
    "50th Anniversary",
    "525i",
    "525xi",
    "528i",
    "528i xDrive",
    "528xi",
    "530i",
    "530xi",
    "535d",
    "535d xDrive",
    "535i",
    "535i xDrive",
    "535xi",
    "540i",
    "545i",
    "550i",
    "550i xDrive",
    "60",
    "60th Anniversary",
    "640i",
    "640i xDrive",
    "645Ci",
    "650i",
    "650i xDrive",
    "7-Passenger",
    "70th Anniversary",
    "740Ld xDrive",
    "740Li",
    "740Li xDrive",
    "740i",
    "740iL",
    "745Li",
    "745i",
    "750Li",
    "750Li xDrive",
    "750i",
    "750i xDrive",
    "750iL",
    "760Li",
    "85",
    "850i",
    "Abarth",
    "ActiveHybrid 3",
    "ActiveHybrid 5",
    "Adrenalin",
    "Advance Package",
    "Advance and Entertainment Packages",
    "Advanced",
    "Aero",
    "Aero SportCombi",
    "Alpha",
    "Altitude",
    "Altitude Edition",
    "American Value Package",
    "Arc",
    "Arc 2.3T",
    "Arc 3.0t",
    "Autobahn",
    "Autobahn PZEV",
    "Autobiography",
    "Autobiography LWB",
    "Avant quattro",
    "Aveo5 1LT",
    "Aveo5 2LT",
    "Aveo5 LS",
    "Aveo5 Special Value",
    "B2300",
    "B2500 SE",
    "B3000",
    "B3000 Dual Sport",
    "B3000 SE",
    "B4000",
    "B4000 SE",
    "BEV",
    "BRABUS cabriolet",
    "BRABUS coupe",
    "Base",
    "Base (1999.5)",
    "Base 7-Passenger",
    "Base PZEV",
    "Bi-Color Edition",
    "Big Horn",
    "BigHorn",
    "Black Edition",
    "Black Tie Edition",
    "Blue",
    "Boss 302",
    "Bullitt",
    "C",
    "C Abarth",
    "C HEMI",
    "C John Varvatos",
    "C John Varvatos Luxury",
    "C Lounge",
    "C Luxury Series",
    "C Pop",
    "C/V",
    "C220",
    "C230",
    "C230 Kompressor",
    "C230 Sport",
    "C240",
    "C240 4MATIC",
    "C240 Luxury",
    "C240 Luxury 4MATIC",
    "C250",
    "C250 Sport",
    "C280",
    "C280 Luxury",
    "C280 Luxury 4MATIC",
    "C300",
    "C300 Luxury",
    "C300 Luxury 4MATIC",
    "C300 Sport",
    "C300 Sport 4MATIC",
    "C32 AMG",
    "C320",
    "C320 4MATIC",
    "C320 Luxury 4MATIC",
    "C320 Sport",
    "C350",
    "C350 4MATIC",
    "C350 Luxury",
    "C350 Luxury 4MATIC",
    "C350 Sport",
    "C400 Sport 4MATIC",
    "C55 AMG",
    "C63 AMG",
    "CDX",
    "CE",
    "CE 7-Passenger",
    "CL500",
    "CL55 AMG",
    "CL550",
    "CL550 4MATIC",
    "CL600",
    "CL63 AMG",
    "CL65 AMG",
    "CLA250",
    "CLA250 4MATIC",
    "CLA45 AMG",
    "CLK320",
    "CLK350",
    "CLK430",
    "CLK500",
    "CLK55 AMG",
    "CLK550",
    "CLK63 AMG",
    "CLS500",
    "CLS55 AMG",
    "CLS550",
    "CLS550 4MATIC",
    "CLS63 AMG",
    "CLS63 AMG 4MATIC S-Model",
    "CX",
    "CXL",
    "CXL Plus",
    "CXL Premium",
    "CXL Turbo",
    "CXL1",
    "CXL2",
    "CXS",
    "Cambiocorsa",
    "Cargo",
    "Cargo Van XL",
    "Cargo Van XL LWB",
    "Cargo Van XLT",
    "Cargo Van XLT LWB",
    "Carrera",
    "Carrera 4",
    "Carrera 4 GTS",
    "Carrera 4S",
    "Carrera Black Edition",
    "Carrera S",
    "Carrera S (Midyear Redesign)",
    "Cartier",
    "Cheyenne",
    "Choice",
    "Cinco",
    "Citadel",
    "Classic",
    "Cloth",
    "Club",
    "Comfort",
    "Concours",
    "Convenience",
    "Convenience Group",
    "Convenience Group 2",
    "Country",
    "Crew",
    "Crossover",
    "Crossroad",
    "Custom",
    "D'elegance",
    "DE",
    "DHS",
    "DTS",
    "DX",
    "DX V6",
    "DX-V6",
    "DX-VP",
    "Dark Flint Edition",
    "Deluxe",
    "Denali",
    "Detonator",
    "Diamond Edition",
    "Diesel",
    "Driver's Edition PZEV",
    "Duro Cross V6",
    "Duro Cross V8",
    "Dynamic Premium",
    "E-150",
    "E-150 XL",
    "E-150 XLT",
    "E-250",
    "E-350 Super Duty",
    "E-350 Super Duty Chateau",
    "E-350 Super Duty XL",
    "E-350 Super Duty XLT",
    "E250 Luxury BlueTEC 4MATIC",
    "E250 Sport BlueTEC",
    "E300D",
    "E320",
    "E320 4MATIC",
    "E320 BLUETEC",
    "E320 BlueTEC",
    "E320 CDI",
    "E350",
    "E350 4MATIC",
    "E350 BlueTEC",
    "E350 Luxury",
    "E350 Luxury 4MATIC",
    "E350 Sport",
    "E350 Sport 4MATIC",
    "E350 Sport BlueTEC",
    "E400 Hybrid",
    "E400 Sport Hybrid",
    "E420",
    "E430",
    "E430 4MATIC",
    "E500",
    "E500 4MATIC",
    "E55 AMG",
    "E550",
    "E550 4MATIC",
    "E550 Sport 4MATIC",
    "E63 AMG",
    "E63 AMG 4MATIC",
    "E63 AMG 4MATIC S-Model",
    "EDGE",
    "EL King Ranch",
    "EL Limited",
    "EL SSV Fleet",
    "EL XL",
    "EL XLT",
    "ES",
    "ES V6",
    "ES-Sport",
    "ES-V6",
    "ESC",
    "ETC",
    "EWB",
    "EX",
    "EX Hybrid",
    "EX PZEV",
    "EX Special Edition",
    "EX Turbo",
    "EX V-6",
    "EX V6",
    "EX-L",
    "EX-L V-6",
    "EX-L V-6 w/Navigation",
    "EX-L w/Navigation",
    "EX-L w/Rear Entertainment",
    "EX-P",
    "EX35",
    "EX35 Journey",
    "EX37",
    "EXT LT",
    "Easy",
    "Ebony Edition",
    "Eco",
    "Eco-Sport",
    "EcoBoost",
    "Econoline",
    "Eddie Bauer",
    "Edge",
    "Edge Plus",
    "Edition 30 PZEV",
    "Electric",
    "Enthusiast",
    "Estate",
    "Executive",
    "Executive GT DuoSelect",
    "Executive L Fleet",
    "Executive PZEV",
    "Executive SULEV",
    "Express",
    "Expresso",
    "F Sport",
    "FE+ S",
    "FE+ SV",
    "FX2",
    "FX35",
    "FX37",
    "FX4",
    "FX4 Level II",
    "FX4 Off-Road",
    "FX50",
    "Family Value",
    "Five",
    "Fleet",
    "Formula",
    "Forte5 EX",
    "Freedom Edition",
    "G",
    "G1500",
    "G25",
    "G25 Journey",
    "G25x",
    "G3500",
    "G37",
    "G37 Journey",
    "G37 Sport",
    "G37x",
    "G500",
    "G55 AMG",
    "G550",
    "G63 AMG",
    "GL",
    "GL (1999.5)",
    "GL 1.8T",
    "GL PZEV",
    "GL TDI",
    "GL V6",
    "GL1",
    "GL2",
    "GL320 BlueTEC",
    "GL320 CDI",
    "GL350 BlueTEC",
    "GL350 BlueTEC 4MATIC",
    "GL4",
    "GL450",
    "GL450 4MATIC",
    "GL550",
    "GL550 4MATIC",
    "GL63 AMG",
    "GLA250 4MATIC",
    "GLE",
    "GLI",
    "GLI 1.8T",
    "GLI VR6",
    "GLK250 BlueTEC 4MATIC",
    "GLK350",
    "GLK350 4MATIC",
    "GLS",
    "GLS (1999.5)",
    "GLS 1.8T",
    "GLS 1.8T 4Motion",
    "GLS PZEV",
    "GLS Special Value",
    "GLS TDI",
    "GLS V6",
    "GLS V6 4Motion",
    "GLS VR6",
    "GLS VR6 (1999.5)",
    "GLS Wolfsburg Edition 1.8T",
    "GLT",
    "GLT SE",
    "GLTS",
    "GLX",
    "GLX 1.8T",
    "GLX 4Motion",
    "GLX Sport",
    "GLX V6",
    "GLX V6 4Motion",
    "GLX VR6",
    "GLX VR6 (1999.5)",
    "GS",
    "GS Convenience",
    "GS PZEV",
    "GS Plus",
    "GS-R",
    "GS-Sport",
    "GSR",
    "GSX",
    "GT",
    "GT Deluxe",
    "GT Limited",
    "GT Limited Edition",
    "GT Premium",
    "GT SULEV",
    "GT-S",
    "GT1",
    "GT2",
    "GTC",
    "GTP",
    "GTS",
    "GTS V6",
    "GTZ",
    "GTZ V6",
    "GX",
    "GXE",
    "GXP",
    "Gran Sport",
    "Grand Sport",
    "Grand Touring",
    "Green Line",
    "H6-3.0 35th Anniversary Edition",
    "H6-3.0 L.L. Bean Edition",
    "H6-3.0 VDC",
    "HD",
    "HD LS",
    "HD SLT",
    "HD XLT",
    "HEV",
    "HF",
    "HPT",
    "HSE",
    "HSE LUX",
    "HT",
    "HX",
    "Hardtop",
    "Harley-Davidson",
    "Heat",
    "Hero",
    "High Altitude Edition",
    "High Country",
    "Highline",
    "Hybrid",
    "Hybrid PZEV",
    "Hybrid PZEV w/Leather and Navigation",
    "Hybrid Premium",
    "Hybrid Sport",
    "Hybrid Touring",
    "Hybrid w/Leather",
    "Hybrid w/Technology Package",
    "I",
    "I4",
    "II",
    "III",
    "IPL",
    "IV",
    "IX",
    "JLS",
    "JLX",
    "JX",
    "JX35",
    "JXi",
    "John Cooper Works",
    "John Cooper Works ALL4",
    "Journey",
    "King Ranch",
    "Komfort",
    "Komfort PZEV",
    "Komfort SULEV",
    "Koup EX",
    "Koup SX",
    "L",
    "L 3.0T quattro",
    "L 35th Anniversary Edition",
    "L 4.0T quattro",
    "L 4.2 quattro",
    "L 7-Passenger",
    "L TDI quattro",
    "L W12 6.3 quattro",
    "L quattro",
    "L.L. Bean Edition",
    "L100",
    "L200",
    "L300",
    "LE",
    "LE 7-Passenger",
    "LE 7-Passenger Mobility Auto Access",
    "LE 8-Passenger",
    "LE Eco",
    "LE Plus",
    "LE Popular Package",
    "LE V6",
    "LE V8",
    "LPT",
    "LS",
    "LS 1500",
    "LS 2500",
    "LS 3500",
    "LS 5 Passenger",
    "LS 7 Passenger",
    "LS Fleet",
    "LS Premium",
    "LS Sport",
    "LS Ultimate",
    "LS V6",
    "LS1",
    "LS2",
    "LSC",
    "LSE",
    "LSi",
    "LT",
    "LT 1500",
    "LT 2500",
    "LT 3500",
    "LT Eco",
    "LT Entertainer",
    "LT Fleet",
    "LT1",
    "LT2",
    "LT2 XFE",
    "LT3",
    "LTZ",
    "LTZ 1500",
    "LTZ Fleet",
    "LW2",
    "LW200",
    "LW300",
    "LX",
    "LX Family Value",
    "LX Fleet",
    "LX Hybrid",
    "LX PZEV",
    "LX Premium",
    "LX Special Edition",
    "LX Special Edition PZEV",
    "LX Special Edition V-6",
    "LX Standard",
    "LX V-6",
    "LX V6",
    "LX Value",
    "LX-P",
    "LX-S",
    "LX-SV",
    "LX-V6",
    "LXi",
    "Laramie",
    "Laramie Longhorn",
    "Laramie Longhorn Edition",
    "Laramie Longhorn Limited Edition",
    "Laramie SLT",
    "Laredo",
    "Lariat",
    "Lariat Limited",
    "Latitude",
    "Latitude X",
    "Leather",
    "Leather Group",
    "Level I",
    "Limited",
    "Limited (1994.5)",
    "Limited 5-Passenger",
    "Limited 7-Passenger",
    "Limited Edition",
    "Limited Edition PZEV",
    "Limited FFV",
    "Limited Fleet",
    "Limited HEV",
    "Limited Jet",
    "Limited PZEV",
    "Limited SULEV",
    "Limited V6",
    "Linear",
    "Linear 2.3T",
    "Longhorn",
    "Lounge",
    "Lux",
    "Lux Limited",
    "Lux Limited PZEV",
    "Lux PZEV",
    "Lux Plus",
    "Lux SULEV",
    "Luxury",
    "Luxury 5 Passenger",
    "Luxury II",
    "Luxury III",
    "Luxury PZEV",
    "M235i",
    "M35h",
    "M37",
    "M37x",
    "M56",
    "M56x",
    "MC",
    "ML320",
    "ML320 BlueTEC",
    "ML320 CDI",
    "ML350",
    "ML350 4MATIC",
    "ML350 BlueTEC",
    "ML350 BlueTEC 4MATIC",
    "ML430",
    "ML500",
    "ML55 AMG",
    "ML550",
    "ML550 4MATIC",
    "ML63 AMG",
    "MR",
    "MR Touring",
    "MV",
    "Mach 1 Premium",
    "Mainstreet",
    "MontanaVision",
    "N400 Roadster",
    "NBX",
    "NISMO",
    "NISMO RS",
    "Natural Gas",
    "Nismo",
    "O-Z Rally",
    "Off-Road",
    "Olympic Gold",
    "One",
    "Outback",
    "Outback Limited",
    "Outback Sport",
    "Outback Sport Special Edition",
    "Overland",
    "PRO-4X",
    "PZEV",
    "Panel LS",
    "Panel LT",
    "Performance",
    "Platinum",
    "Platinum Edition",
    "Platinum FFV",
    "Plus",
    "Pop",
    "Portfolio",
    "Power Wagon",
    "PreRunner",
    "PreRunner V6",
    "Premier",
    "Premiere",
    "Premium",
    "Premium 1",
    "Premium 1 Turbo",
    "Premium 2",
    "Premium 2 Turbo",
    "Premium Cartier",
    "Premium Fleet",
    "Premium Group",
    "Premium I",
    "Premium I Group",
    "Premium II Group",
    "Premium III Group",
    "Premium Luxury",
    "Premium Package",
    "Premium Plus",
    "Premium Plus quattro",
    "Premium Signature",
    "Premium quattro",
    "Prerunner",
    "Prestige",
    "Prestige Premium",
    "Prestige quattro",
    "Pro-4X",
    "Pure",
    "Pure Plus",
    "Pure Premium",
    "QX56",
    "R",
    "R-Design",
    "R-Line",
    "R-Line PZEV",
    "R/T",
    "R/T Plus",
    "R/T Scat Pack",
    "R320 BlueTEC",
    "R320 CDI",
    "R350",
    "R350 4MATIC",
    "R350 BlueTEC",
    "R500",
    "RE:FLEX",
    "RE:MIX",
    "RS",
    "RT",
    "RT Fleet",
    "RTL",
    "RTL w/Leather",
    "RTL w/Leather and Navigation",
    "RTS",
    "RTX",
    "Ralliart",
    "Ralliart V6",
    "Rallye",
    "Red Line",
    "Renegade",
    "Ribelle",
    "Rio5 LX",
    "Rio5 SX",
    "Rocky Mountain",
    "Rubicon",
    "Rush",
    "S",
    "S  w/Soft Top",
    "S 4Motion",
    "S 5 Passenger",
    "S 5-Passenger",
    "S 7 Passenger",
    "S 7-Passenger",
    "S ALL4",
    "S Anniversary Edition",
    "S Automatic",
    "S E-Hybrid",
    "S Hybrid",
    "S Krom Edition",
    "S PZEV",
    "S Plus",
    "S Premium",
    "S Q4",
    "S SULEV",
    "S Special Edition",
    "S V6",
    "S V8",
    "S320 LWB",
    "S320 SWB",
    "S350",
    "S350 BlueTEC 4MATIC",
    "S400 Hybrid",
    "S420",
    "S430",
    "S430 4MATIC",
    "S500",
    "S500 4MATIC",
    "S55 AMG",
    "S550",
    "S550 4MATIC",
    "S600",
    "S63 AMG",
    "S63 AMG 4MATIC",
    "S65 AMG",
    "SC",
    "SC-V6",
    "SC1",
    "SC2",
    "SD",
    "SE",
    "SE 20th Anniversary",
    "SE 4Motion",
    "SE 8-Passenger",
    "SE Comfort",
    "SE Fleet",
    "SE HO",
    "SE Limited",
    "SE Luxury",
    "SE Off Road",
    "SE Off-Road",
    "SE PZEV",
    "SE PZEV w/Connectivity",
    "SE Plus",
    "SE Premium",
    "SE S/C",
    "SE SULEV",
    "SE Sport",
    "SE V6",
    "SE w/Leather and Navigation",
    "SE-R",
    "SE-R Spec V",
    "SE-V6",
    "SE-V6 Desert Runner",
    "SE-V6 Dessert Runner",
    "SE1",
    "SE2",
    "SE3",
    "SEL",
    "SEL 4Motion",
    "SEL Deluxe",
    "SEL Fleet",
    "SEL PZEV",
    "SEL Plus",
    "SEL Premium",
    "SEL Premium PZEV",
    "SES",
    "SES Deluxe",
    "SH-AWD",
    "SH-AWD w/Advance Package",
    "SH-AWD w/Advance and Entertainment Packages",
    "SH-AWD w/Technology Package",
    "SH-AWD w/Technology and Entertainment Packages",
    "SHO",
    "SL",
    "SL 1500",
    "SL SULEV",
    "SL1",
    "SL2",
    "SL320",
    "SL500",
    "SL55 AMG",
    "SL550",
    "SL600",
    "SL63 AMG",
    "SL65 AMG",
    "SLE",
    "SLE 1500",
    "SLE V6",
    "SLE-1",
    "SLE-2",
    "SLE1",
    "SLE2",
    "SLE2 XFE",
    "SLK230",
    "SLK230 Kompressor",
    "SLK250",
    "SLK280",
    "SLK300",
    "SLK320",
    "SLK350",
    "SLK55 AMG",
    "SLS",
    "SLS Sport",
    "SLT",
    "SLT 1500",
    "SLT Plus",
    "SLT-1",
    "SLT-2",
    "SLT1",
    "SLT1 1500",
    "SLT1 XFE",
    "SLT2 1500",
    "SP23 Special Edition",
    "SPORT",
    "SR",
    "SR FFV",
    "SR5",
    "SR5 FFV",
    "SR5 V6",
    "SRT",
    "SRT-10",
    "SRT-4",
    "SRT-8",
    "SRT4",
    "SRT8",
    "SRT8 392",
    "SRT8 Core",
    "SRT8 Superbee",
    "SS",
    "SS/T",
    "SSE",
    "SSEi",
    "SSV Fleet",
    "ST",
    "STI",
    "STI Launch Edition",
    "STI Limited",
    "STS",
    "STX",
    "SV",
    "SV Hybrid",
    "SV6",
    "SVE-V6",
    "SVT",
    "SVT Cobra",
    "SVT Lightning",
    "SVT Raptor",
    "SW1",
    "SW2",
    "SX",
    "SX Premium",
    "SX Turbo",
    "SXL",
    "SXT",
    "SXT Fleet",
    "SXT Plus",
    "Sahara",
    "Series II",
    "Shock",
    "Si",
    "Signature",
    "Signature L",
    "Signature Limited",
    "Silverado",
    "Spec",
    "Special",
    "Special Edition",
    "Special Edition V-6",
    "Special Value",
    "Spectra5",
    "Spectra5 SX",
    "Spider",
    "Spider F1",
    "Splash",
    "Sport",
    "Sport 2.0T",
    "Sport Edition",
    "Sport GT",
    "Sport GT S Automatic",
    "Sport GTS",
    "Sport JLX",
    "Sport Limited",
    "Sport PZEV",
    "Sport S",
    "Sport SE",
    "Sport SLS",
    "Sport SULEV",
    "Sport V6",
    "Sport w/Navigation",
    "SportBack",
    "SportBack GTS",
    "SportBack Technology",
    "SportCombi",
    "SportCross",
    "SportWagen S",
    "SportWagen S PZEV",
    "SportWagen SE",
    "SportWagen SE PZEV",
    "SportWagen TDI",
    "Sports 2.5 X",
    "Spyder",
    "Standard",
    "Stingray",
    "Stingray Z51",
    "Style",
    "Summit",
    "Super",
    "Supercharged",
    "Supercharged LWB",
    "Supercharged Limited Edition",
    "T5",
    "T5 Drive-E",
    "T5 Drive-E Premier",
    "T5 Premier",
    "T5 R-Design",
    "T5 Special Edition",
    "T5 Version 1.0",
    "T6",
    "T6 Elite",
    "T6 R-Design",
    "TDI",
    "TDI Cup Edition",
    "TDI Executive",
    "TDI Loyal Edition",
    "TDI Lux",
    "TDI Premium Plus quattro",
    "TDI Premium quattro",
    "TDI Prestige quattro",
    "TDI SE",
    "TDI SEL Premium",
    "TDI Sport",
    "TRD PRO",
    "TS",
    "TSI S",
    "TSI SE",
    "TSi",
    "Technology Package",
    "Technology and Entertainment Packages",
    "Three",
    "Tiptronic",
    "Titanium",
    "Touring",
    "Touring Edition",
    "Touring Elite",
    "Touring Fleet",
    "Touring Group",
    "Touring Plus",
    "Touring V-6",
    "Touring w/Navigation and Rear Entertainment",
    "Touring-L",
    "Track Edition",
    "Tradesman",
    "Trail",
    "TrailBlazer",
    "Trailblazer",
    "Trailhawk",
    "Trans Am",
    "Trekking",
    "Tremor",
    "Triple White",
    "Triple White PZEV",
    "Tundra",
    "Tundra FFV",
    "Tundra Grade",
    "Turbo",
    "Turbo 60's Edition",
    "Turbo Fender Edition",
    "Turbo PZEV",
    "Turbo PZEV Fender Edition",
    "Turbo Premium",
    "Turbo S",
    "Turbo4 Premium",
    "Two",
    "Type SH",
    "Type-S",
    "Ultimate",
    "Ultimate Adventure",
    "Ultra",
    "Unlimited",
    "Unlimited 70th Anniversary",
    "Unlimited Freedom Edition",
    "Unlimited Rubicon",
    "Unlimited Rubicon Hard Rock",
    "Unlimited Sahara",
    "Unlimited Sport",
    "Unlimited Sport RHD",
    "Unlimited X",
    "Uptown",
    "V",
    "V10 TDI",
    "V6",
    "V6 Executive",
    "V6 Luxury",
    "V6 Luxury Sport",
    "V6 Premium",
    "V6 R-Line",
    "V6 SE",
    "V6 SEL Premium",
    "V6 TDI",
    "V8",
    "V8 FSI",
    "V8 HSE",
    "V8 Luxury",
    "V8 S",
    "V8 SE",
    "V8 Sport",
    "VDC",
    "VE",
    "VIII",
    "VP",
    "VR-X",
    "VR6",
    "VR6 4Motion",
    "VR6 4Motion Executive",
    "VR6 Executive",
    "VR6 FSI",
    "VR6 Lux",
    "VR6 Sport",
    "Value",
    "Value Edition",
    "Value Edition PZEV",
    "Value Leader",
    "Value Package",
    "Vanden Plas",
    "Vector",
    "Volante",
    "Vsport Platinum",
    "Vsport Premium",
    "W8 4Motion",
    "WRX",
    "WRX Limited",
    "WRX Premium",
    "WRX STI",
    "WRX STI Limited",
    "WRX STi",
    "WRX TR",
    "WS",
    "Wagon",
    "Wagon Titanium LWB",
    "Wagon XLT",
    "Wagon XLT LWB",
    "Wagon XLT Premium",
    "Wagon XLT SWB",
    "Warner Bros.",
    "Warner Brothers",
    "Wolfsburg",
    "Wolfsburg Edition",
    "Wolfsburg Edition 4Motion",
    "Wolfsburg Edition PZEV",
    "Work",
    "Work Truck",
    "X",
    "X Special Edition",
    "X-Runner V6",
    "XC",
    "XE",
    "XE (1997.5)",
    "XE Desert Runner",
    "XE V6",
    "XE-V6",
    "XE-V6 Dessert Runner",
    "XFE",
    "XFR",
    "XJ6",
    "XJ6 Sovereign",
    "XJ6 Vanden Plas",
    "XJ6L",
    "XJ8",
    "XJ8 L",
    "XJ8L",
    "XJL",
    "XJL Portfolio",
    "XJL Supercharged",
    "XJR",
    "XJR LWB",
    "XK",
    "XK8",
    "XKR",
    "XL",
    "XLE",
    "XLE 7-Passenger",
    "XLE 8-Passenger",
    "XLE Limited 7-Passenger",
    "XLE Premium",
    "XLE Touring",
    "XLE Touring SE",
    "XLE V6",
    "XLS",
    "XLS Choice",
    "XLS Popular",
    "XLS Sport",
    "XLS Value",
    "XLT",
    "XLT Appearance",
    "XLT Choice",
    "XLT FX4",
    "XLT NBX",
    "XLT Popular",
    "XLT Premium",
    "XLT Sport",
    "XLT Super Club Wagon",
    "XLT Value",
    "XR",
    "XR7",
    "XRS",
    "XS",
    "XSE",
    "XSport",
    "XXV",
    "Xtreme",
    "Z/28",
    "Z06",
    "Z06 Competition Sport Spec Ed",
    "Z24",
    "Z28",
    "Z34",
    "Z51",
    "Z71",
    "Z71 LS",
    "Z71 LT",
    "Z71 SL",
    "Z71 SLE",
    "Z71 SLE Base",
    "Z85",
    "Z85 LS Base",
    "Z85 SL",
    "Z85 SLE",
    "ZL1",
    "ZQ8",
    "ZQ8 LS",
    "ZR1",
    "ZR2",
    "ZTS",
    "ZTW",
    "ZX2",
    "ZX2 Deluxe",
    "ZX3",
    "ZX3 Power Premium",
    "ZX3 S",
    "ZX3 SES",
    "ZX4 SE",
    "ZX4 SES",
    "ZX4 ST",
    "ZX5",
    "ZX5 Premium",
    "ZX5 SE",
    "ZX5 SES",
    "ZXW SES",
    "base",
    "eC",
    "eL",
    "eX",
    "electric drive cabriolet",
    "electric drive coupe",
    "ex v-6",
    "i",
    "i Grand Touring",
    "i SV",
    "i Sport",
    "i Sport Value Edition",
    "i Touring",
    "i Touring Plus",
    "i-280 S",
    "i-290 LS",
    "i-290 S",
    "ls",
    "passion",
    "passion cabrio",
    "passion cabriolet",
    "passion coupe",
    "pure",
    "pure coupe",
    "quattro",
    "s",
    "s Grand Touring",
    "s Sport",
    "s Sport Value Edition",
    "s Touring",
    "s Touring Plus",
    "sDrive28i",
    "sDrive30i",
    "sDrive35i",
    "sDrive35is",
    "t Turbo",
    "x",
    "xDrive28d",
    "xDrive28i",
    "xDrive30i",
    "xDrive35d",
    "xDrive35i",
    "xDrive35i Premium",
    "xDrive48i",
    "xDrive50i",
]

CAR_BODIES = [
    "ACCESS CAB",
    "BEETLE CONVERTIBLE",
    "CAB PLUS",
    "CAB PLUS 4",
    "CLUB CAB",
    "CONVERTIBLE",
    "COUPE",
    "CREW CAB",
    "CREWMAX CAB",
    "CTS COUPE",
    "CTS WAGON",
    "CTS-V COUPE",
    "CTS-V WAGON",
    "DOUBLE CAB",
    "E-SERIES VAN",
    "ELANTRA COUPE",
    "EXTENDED CAB",
    "G CONVERTIBLE",
    "G COUPE",
    "G SEDAN",
    "G37 CONVERTIBLE",
    "G37 COUPE",
    "GENESIS COUPE",
    "GRANTURISMO CONVERTIBLE",
    "HATCHBACK",
    "KING CAB",
    "KOUP",
    "MEGA CAB",
    "MINIVAN",
    "NAVITGATION",
    "PROMASTER CARGO VAN",
    "Q60 CONVERTIBLE",
    "Q60 COUPE",
    "QUAD CAB",
    "RAM VAN",
    "REGULAR CAB",
    "REGULAR-CAB",
    "SEDAN",
    "SUPERCAB",
    "SUPERCREW",
    "SUV",
    "TRANSIT VAN",
    "TSX SPORT WAGON",
    "VAN",
    "WAGON",
    "XTRACAB",
]


